name: cd-build-push-dockerhub
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/cd-aws.yaml"
  workflow_dispatch: # manual

jobs:
  #  build-push:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #     with:
  #       fetch-depth: 0 # to get all tags
  #   - uses: docker/setup-buildx-action@v3
  #   - run: docker buildx ls
  #   - uses: docker/login-action@v3
  #     with:
  #       registry: docker.io
  #       username: ${{ secrets.DOCKERHUB_USERNAME }}
  #       password: ${{ secrets.DOCKERHUB_TOKEN }}
  #   - run: ./build-push.sh
  #     working-directory: ./api
   deploy:
    runs-on : ubuntu-latest
  #  needs: build-push
    environment: 
      name: production
    steps: 
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

