name: cd-build-push-dockerhub
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/cd-build-push.yaml"
  workflow_dispatch: # manual

jobs:
   build-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # to get all tags
    - uses: docker/setup-buildx-action@v3
    - run: docker buildx ls
    - uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: ./build-push.sh
      working-directory: ./api