name: test_gha
on:
  push:
    branches:  #whenever a push is regitered via commit /git push
      - main
  workflow-disptach:
  jobs:
    print-testfile:
      runs-on: ubuntu-latest
      steps:
    - name: checkout repo code
      uses: actions/checkout@v4
    - name: Check and display testfile
      run: |
          if [ -f TestFile ]; then
            echo "Contents of helloworld.txt:"
            cat TestFile
          else
            echo "Error: TestFile not found"
            exit 1
          fi
