name: test_gha
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  print-testfile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo code
        uses: actions/checkout@v4
      - name: Check and display testfile
        run: |
            if [ -f TestFile ]; then
              echo "Contents of TestFile:"
              cat TestFile
            else
              echo "Error: TestFile not found"
              exit 
            fi
