name: upper-build
on:
 push:
  paths:
  - "./upper/**"
  - ".github/workflows/go-Build_upper.yml"
 workflow_dispatch:

jobs:
  build-go:
    runs-on: ubuntu-latest
    steps:
     - run: pwd && ls -al
     - name: Checkout repository
       uses: actions/checkout@v4
     - run: pwd && ls -al
     - run: go version
     - name: Setup a go environment
       uses: actions/setup-go@v5
       with:
        go-version: '1.22'
     - run: go version
     - name: Download dependencies
       run: go mod download
       working-directory: ./upper
     - name: Build and Test
       run: |
         ls
         go build
         ls
         go test
         ./upper arnesh dey
       working-directory: upper
