name: integrations-test
on: 
    push:
      paths:
        - ".github/workflow/integration-test.yml"
    workflow_dispatch: # manual
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: env | sort
      - run: echo "RANDOM_PASSWORD=$(LC_ALL=C tr -dc A-Za-z0-9 </dev/urandom | head -c 12)" >> "$GITHUB_ENV"
      - run: echo "$RANDOM_PASSWORD / ${{ env.RANDOM_PASSWORD }}"
      - run: env | sort
  