name: pythonNodejsVersions
on:
  push:
  workflow_dispatch:
jobs:
  python-install:
    runs-on: ubuntu-latest
    steps:
      - name: Check_Repo
        uses: actions/checkout@v4
      - name: install python library
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -V
  nodejs-install:
    runs-on: ubuntu-latest
    steps:
      - name: install nodejs library
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          node -v
          npm -v
          npm install    
          

    
  
    
