name: OpenAI Chat on PR
permissions:
  contents: read
  pull-requests: write
on:
  issue_comment:
    types: [created]

jobs:
  chat:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/chat')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate OpenAI Response
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          python -c "
          from openai import OpenAI
          import os
          import json
          client = OpenAI(api_key=os.getenv('OPENAI_API_KEY'))
          response = client.chat.completions.create(
              model='gpt-4.1-nano',
              messages=[
                  {'role': 'system', 'content': 'You are a helpful assistant responding to GitHub PR comments.'},
                  {'role': 'user', 'content': os.getenv('COMMENT_BODY')}
              ]
          )
          comment = response.choices[0].message.content
          with open('comment.md', 'w') as f:
              f.write(comment)
          "

      - name: Post Comment to PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.issue.number }} --body-file comment.md
        shell: bash
