name: publishing_artificats to release
on:
  push:
    paths:
      - "./upper/**"
      - ".github/workflows/PublishArtifactsRelease.yml"
  workflow_dispatch: # manual trigger
jobs:
    cross:
      permissions:
        contents: write
      runs-on: ubuntu-latest
      defaults:
          run:
            working-directory: upper
      steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-go@v5
            with:
                go-version: '1.22'
                cache-dependency-path: ./upper/go.sum
          - run: |
              ls -ltr
              chmod +x build_xplat.sh
              ./build_xplat.sh
          - uses: softprops/action-gh-release@v2
            with:
                files: ./upper/bin/upper*
                body: "Release for GO based ALL CAPS tool"
                tag_name: ${{ github.ref_name }}
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
