name: upper-image
on: 
    push:
        paths:
            - "./upper/**"
            - ".github/workflows/upper-image.yml"
    workflow_dispatch: # manual
permissions:
    contents: read #optional, not required in case of Public Repository
    packages: write

jobs:
    image:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: docker version
            - run: docker image build -t upper .
              working-directory: ./upper
            - name: test-it
              run: docker container run upper hello arnesh
            - uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.repository_owner }} #devopsbyarneshdey
                password: ${{ secrets.GITHUB_TOKEN }}
            - run: docker tag upper ghcr.io/devopsbyarneshdey/upper:latest
            - run: docker tag upper ghcr.io/devopsbyarneshdey/upper:${{ github.ref_name }}
            - run: docker push ghcr.io/devopsbyarneshdey/upper:latest
            - run: docker push ghcr.io/devopsbyarneshdey/upper:${{ github.ref_name }}